---
title: "DSA301 Project"
author: "Everyone"
output: html_document
---

```{r cars}
# install.packages("pageviews")
# install.packages("jsonlite")
# install.packages("lubridate")
library(jsonlite)
library(pageviews)
library(lubridate)
library(dplyr)
library(forecast)
library(urca)
library(TSstudio)
rm(list = ls())
```

Getting the daily data
```{r pressure, echo=FALSE}
project = "en.wikipedia.org"
access = "all-access"
agent = "all-agents"
granularity = "daily"
start = "2015010100"
end = "2022013123"
url_daily = sprintf("https://wikimedia.org/api/rest_v1/metrics/pageviews/aggregate/%s/%s/%s/%s/%s/%s", project, access, agent, granularity, start, end)
url_hourly = sprintf("https://wikimedia.org/api/rest_v1/metrics/pageviews/aggregate/%s/%s/%s/%s/%s/%s", project, access, agent, "hourly", start, end)
daily_data = fromJSON(txt=url_daily)$items
hourly_data = fromJSON(txt= url_hourly)$items

```

Converting Raw Data to Time Series
```{r}
msts_wiki_daily <- daily_data$views %>% 
  msts(seasonal.periods = c(7, 365), 
       start = decimal_date(as.Date("2015-07-01")))
```

Visualising & Decomposing Time Series
```{r}
autoplot(msts_wiki_daily)
wiki_daily_decomp <- mstl(msts_wiki_daily)
autoplot(wiki_daily_decomp)
```

Transforming Seasonal Adjusted Component
```{r}
seasadj_wiki <- seasadj(wiki_daily_decomp)

#Test stat = 0.0094
seasadj_wiki %>% 
  diff(lag =1)%>%
  ur.kpss()%>%
  summary()

#Test stat = 0.0149 
seasadj_wiki %>% 
  diff(lag =7)%>%
  ur.kpss()%>%
  summary()

#Test stat = 0.0055
seasadj_wiki %>% 
  diff(lag =7)%>% 
  diff(lag = 1)%>%
  ur.kpss()%>%
  summary()

#Test stat = 1.2046
seasadj_wiki %>% 
  diff(lag =365)%>%
  ur.kpss()%>%
  summary()

#Test stat = 0.0117
seasadj_wiki %>% 
  diff(lag =365)%>% 
  diff(lag = 1)%>%
  ur.kpss()%>%
  summary()

trans_seasadj_wiki <- seasadj_wiki %>% diff(lag = 7)
autoplot(trans_seasadj_wiki)
```

Splitting Test & Train Data
```{r}
wiki_daily_split <- ts_split(msts_wiki_daily, sample.out = 482)
```


Fitting Models on Transformed Data
```{r}
#Benchmark Models (Need to clarify with Prof on how to transform back after we only apply differencing to seasonal adjusted component. Refer to Lecture 6 hmwk 2 code (he applied differencing to time series before decomposition))


#ARIMA Models
ggtsdisplay(trans_seasadj_wiki)
Pacf(trans_seasadj_wiki)
Acf(trans_seasadj_wiki)


#Testing out Seasonal ARIMA with stlm. NEED HELP WITH READING ACF & PACF!!! 
#GRILL PROF ON THURSDAY

auto.arima(ts(msts_wiki_daily, frequency = 7))

m1 <- Arima(msts_wiki_daily,order=c(2,0,3), 
         seasonal = list(order = c(1,1,2), period = 7))
m1


m2 <- Arima(msts_wiki_daily,order=c(2,0,3), 
         seasonal = list(order = c(0,1,2), period = 7))
m2


f1 = stlm(wiki_daily_split$train, modelfunction = Arima, order=c(2,0,3), 
         seasonal = list(order = c(1,1,2), period = 7), robust = T)

f2 = stlm(wiki_daily_split$train, modelfunction = Arima, order=c(2,0,3), 
         seasonal = list(order = c(0,1,2), period = 7), robust = T)

checkresiduals(forecast(f1))
checkresiduals(forecast(f2))

accuracy(forecast(f1), wiki_daily_split$test)
accuracy(forecast(f2), wiki_daily_split$test)


autoplot(msts_wiki_daily)+autolayer(forecast(f2), PI = F)

```


```{r}
#Miscellaneous

wiki_daily_single_yearly <- msts(ts(msts_wiki_daily), seasonal.periods = 365.25)
wiki_daily_single_weekly <- msts(ts(msts_wiki_daily), seasonal.periods = 7)


wiki_daily_split <- ts_split(msts_wiki_daily, sample.out = 482)
wiki_daily_single_yearly_split <- ts_split(wiki_daily_single_yearly, sample.out = 482)
wiki_daily_single_weekly_split <- ts_split(wiki_daily_single_weekly, sample.out = 482)
accuracy(stlf(wiki_daily_split$train), wiki_daily_split$test)
accuracy(stlf(wiki_daily_single_yearly_split$train), wiki_daily_single_yearly_split$test)
accuracy(stlf(wiki_daily_single_weekly_split$train), wiki_daily_single_weekly_split$test)
```

